### ISSUE TITLE
various rom issues and system 32/multi 32 problems (WiiU Core)

### ISSUE THREAD

**Issue by 1seam1** [libretro/mame2003-libretro#70] opened 2016-12-14 21:35 UTC
The following are from testing done using the latest WiiU core.

MAME
dbz2 - has minor grafx glitches
lucky and wild - cant aim to fire. some grafx glitches
mk2-3 - works perfect but has low volume
ninja baseball batman - bad audio, some grafx glitches
primal rage - loads, way too slow(probably will never be fullspeed), has some grafx glitches
mk3u - runs great, has minor grafx glitches
crusnusa - asks to hit enter key to proceed, cant assign key though
sonic arcade - suggest trying "sonicp" rom instead, which crashes mame

system 32: not loading at all(maybe mame2003 doesnt support system32/multi32?)
alien3
dbzvrvs
ga2
gaxeduel
rad mobile
rad rally

system multi 32: not loading
outrunners

konami gx hardware: not loading
Salamander2

edit: also im unsure as to whether or not the PGM driver is functional in FBA. Dodonpachi II and Demon Front wont load and they are verified roms from the correct set.

**Comment by markwkidd** [comment] 2016-12-20 02:22
Can you confirm that those ROMs work correctly in the original standalone version of MAME 0.78? At first glance, your list may contain some titles that never worked 100% in MAME 0.78 to begin with.

That would be a useful clue as to whether these are the result of a regression during the translation to a libretro core rather than a lack of support inherent to this version of MAME. 

I have had good luck running MAME 0.78 in Windows 10 even though it was meant for Windows XP.

**Comment by 1seam1** [comment] 2016-12-20 04:27
sure, i just tested them all in .78 in windows xp. here are the results:

alien3     works fine
cruisnusa     works fine
dbz vs      doesnt load
dbz2         same as wii
ga2           works, characters shadow looks odd
gaduel                   didnt load
lucky and wild        works fine
ninja baseball batman    works fine
outrunners      works fine
primal rage      works fine
rad mobile       works fine
rad rally          stays at networking check screen
salamader2     didnt load
sonic     cant seem to get ingame, just says waiting after choosing character
mk3u     same as wii

**Comment by markwkidd** [comment] 2016-12-20 04:29
Thank you! That adds some very useful info to the report.

**Comment by rb6502** [comment] 2017-12-28 01:22
For MK games, you have to turn up the volume in service mode (press F2 to enter service mode).  This is true all the way to today's 0.193 release.

**Comment by markwkidd** [comment] 2018-04-24 10:12
@1seam1 if you're still interested in this project, could you try these now in mame2003-plus? And then report this list over there if there are still problems?

We have testing a lot of fixes to mame2003 over in mame2003-plus, and if these haven't already been addressed (which I suspect they might) then we can make a more active investigation there.

The github link is https://github.com/libretro/mame2003-plus-libretro

**Comment by 1seam1** [comment] 2018-04-26 05:06
ok ill test it out here in the next few days

**Comment by markwkidd** [comment] 2018-10-15 21:21
I'm going to close this issue, but please do still feel free to continue on with us over at the mame2003-plus repo: https://github.com/libretro/mame2003-plus-libretro

**Comment by markwkidd** [comment] 2018-10-15 21:31
We've had several tweaks to the makefile specifically for WiiU, not to mention other fixes that may have touched on this issue. For example there should no longer be low default volume in mk2 and clones due to my adding an NVRAM bootstrap for those romsets.

But anyway I'd like to know results on the non MK2 titles mainly because of the slightly different compiler flags for WiiU versus standard mame2003. But if no one is around to test on WiiU then seems like a nartural time to close the issue to me. An alternative would be to try to drum up someone on discord to test

**Comment by markwkidd** [comment] 2018-10-15 21:34
There has also been a backported fix to the same driver as Ninja Baseball Batman in mame2003-plus -- did it affect that romset? 

Anyway I could be a tiny bit more researched but I hope you get my point. This issue is out of date and with no one to follow up it doesn't seem like the best place to start working on these other issues.

**Comment by dankcushions** [comment] 2018-10-15 21:47
we close issues when they are confirmed fixed. there's no purpose to that.

**Comment by markwkidd** [comment] 2018-10-15 21:49
I also close issues when the OP is not responsive and there is no one else to test. I'd be willing to agree to some standard convention on how to manage issues if some group has created such a tool. Otherwise I'd say it's perfectly within convention to close this one and I'm leaving it that way unless a WiiU tester surfaces.

**Comment by dankcushions** [comment] 2018-10-15 22:00
6 months is hardly a long time to wait in libretro land. I don't see any purpose in closing a valid issue ever. What's the harm if it stays open until a tester appears? Are you anticipating people going through the closed issues to look for those that are closed but NOT fixed?

**Comment by markwkidd** [comment] 2018-10-15 22:02
No I'm saying that this is obsolete and a dead end as an issue ticket. Let's hear from someone who is around to work through the troubleshooting process, then point them to the best starting point for the investigation.

**Comment by markwkidd** [comment] 2018-10-15 22:05
One reason it's common practice for a maintainer to post a new comment in an abandoned issue before closing it is that it gives people who still want to be involved a chance to speak up. It's great when people do reply, which gives me a chance to reopen an issue with the excitement that there is still energy moving forward.

However this exchange has gone into some pointless meta territory about when to close issues. Please feel free to open a new issue about that where we can have a discussion. If someone with a WiiU still cares enough to be reading this, please contact me or open a new issue.

**Comment by markwkidd** [comment] 2018-10-16 03:00
I've re-opened the issue at @twinaphex 's request. I apologize for being short tempered. I'm posting on Discord now to see if we can drum up someone to test this.

I monitor the gbatemp forums and occasionally I respond to mame2003 support requests there but I'd rather try for a day or two on the libretro discord server first.

**Comment by markwkidd** [comment] 2018-10-17 17:43
@gblues has been generous enough to test these romsets. The good news is that things seem to be working.

> alien3 works
> crusnusa boots but it tries to do a controller calibration, assuming it's good
> ga2 works
> luckywld works
> nbbatman works
> primrage works
> radm works

gblues goes on to hypothesize:
>  I think either they have bad roms, or they're not waiting long enough (mame2003 core takes a really long time to boot up on Wii U, most likely due to slow I/O decompressing the ROMs)

**Comment by markwkidd** [comment] 2019-01-18 14:45
I feel that we conclusively have determined that these romsets are working. As a bonus, starting yesterday MK2 will even boot up at normal volume :)

**Closed by markwkidd** 2019-01-18 14:45 UTC
