### ISSUE TITLE
[$250 BOUNTY] Regression: mame2003 renders vectors worse than MAME 0.78

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#332] opened 2018-03-10 08:51 UTC
The intention of the bounty is to improving mame2003's vector rendering quality to parity with mame0.78. 

## Bounty page
https://www.bountysource.com/issues/56042669-regression-mame2003-renders-vectors-worse-than-mame0-78

## Visual Difference

This image demonstrates the differing ways that mame0.78 and mame2003 render `tempest.zip` when running fullscreen on the same system with all settings at their defaults. Note that the listed resolutions are for the final rendered version and as far as I know are not necessarily reflective of the resolution being used internally by MAME, especially for MAME 0.78.
.
![tempest-comparison](https://user-images.githubusercontent.com/19554678/37240154-b4d442ca-2415-11e8-977a-d3c301cd23d2.png)

## Criteria 

Antialiasing and rendering vectors at high resolution are essential to faithful vector emulation and it seems likely that the issue is related to the MAME settings `options.antialias`, `options.vector_width`, and `options.vector_height`. 

1. The vector width and height code had to be [modified in arbitrary (and possibly incorrect) ways](https://github.com/libretro/mame2003-libretro/issues/30#issuecomment-370135190) to keep it from crashing mame2003 and retroarch. The result of that discovery allowed me to create a core option exposing vector resolution, but when activated vectors do (sort of!) render at a high resolution, but there are major scaling/rendering issues when this is enabled.
2. The antialias setting crashes mame and retroarch when enabled. It is exposed as a core option but it is set to only allow the `disabled` state.

**Further reading**: This issue springs from an earlier discussion where we have [learned at least a few things about what is going on](https://github.com/libretro/mame2003-libretro/issues/30)

**Comment by markwkidd** [comment] 2018-03-10 08:56
@r-type a while back you told me that I should reallocate the $10 bounty from a mame2000 bounty to another issue. That finally closed out this week, so I'm allocating it here. Thank you!

@caver01 you seemed like you are as interested in me in seeing this happen so I wanted to tag you. If you also want to contribute to the bounty, here is a direct link : https://www.bountysource.com/issues/56042669-regression-mame2003-renders-vectors-worse-than-mame0-78

**Comment by markwkidd** [comment] 2018-03-25 01:07
One thing I can add is that the antialiasing code in mame2003 is essentially identical to the current AdvanceMAME antialias code.

To me that implies too things: mame2003 vectors should be able to look just as good as AdvanceMAME and that the issue may lie in either the libretro port or something like compiler tags.

**Comment by grant2258** [comment] 2018-04-12 15:03
set the core sample rate to 22050 should fix the timing issues up and restart mame2003

**Comment by grant2258** [comment] 2018-04-13 16:27
well these vector games run at 30fps the fix should fix it just need the push to go forward. Dont know anything about bountys :)

**Comment by markwkidd** [comment] 2018-04-13 23:06
I just found what I think is a clue: https://github.com/libretro/mame2003-libretro/blob/master/src/mame.c#L698-L699

That function call is not commented out in mame 0.78.

@Wilstorm yes you can contribute to a bounty via PayPal. I personally did use my Github account to set up my account with Bountysource which seemed smooth enough.

**Comment by markwkidd** [comment] 2018-04-16 04:25
It's exciting to have new developments in this issue! As soon as possible I
will create a test compile that enables the antialias core option and see
how that combines with your fix

**Comment by grant2258** [comment] 2018-04-16 04:36
just grab from my github mke sure you delete and core over rides you have for the game and mame. Let me know if there is any change mark

**Comment by caver01** [comment] 2018-04-16 04:47
Great to see some momentum. Markwkidd, your test with anti-alias is important, but will you also be able to check higher resolutions? The beauty of the vector features are the combination of beam intensity, width, flicker, anti-alias with native display resolution.

**Comment by markwkidd** [comment] 2018-04-16 04:58
I'm afraid to say that I don't see an improvment in mame2003 function
either with the resolution multiplier or with the vector antialias function
enabled :(

**Comment by grant2258** [comment] 2018-04-16 05:00
Is the the last of the major bugs mark ?

**Comment by markwkidd** [comment] 2018-04-16 05:08
Yep, this is the last major bug as far as I know.

**Comment by ewancube** [comment] 2018-09-17 21:14
Bounty bumped to $250

**Comment by markwkidd** [comment] 2018-09-17 21:19
Big thanks @ewancube !

**Comment by Wilstorm** [comment] 2018-09-18 03:53
@ewancube - Nice! :)

**Comment by UDb23** [comment] 2018-09-18 22:30
@ewancube Great!! Thanks.

**Comment by nayslayer** [comment] 2018-10-10 21:38
Hey there. I've done some digging and figured out the antialiasing part of the problem - it comes down to options being parsed incorrectly in the libretro port: the beam width variable shouldn't be set to an integer multiplier, it should instead be calculated as (int)((float) f_beam * 0x00010000) so that the result is a fixed-point number with a 16 bits even part and a 16 bits fractional part. This leads to calculated beam width being smaller than the rounding error and therefore causes an infinite loop when drawing antialiased lines. Setting the right internal resolution is somewhat tricky, though. I'll make a pull request once I figure it out.

**Comment by markwkidd** [comment] 2018-10-10 21:39
That is very exciting to hear!

**Comment by nayslayer** [comment] 2018-10-12 15:57
Done the necessary changes. Will test some more, then make a PR. If you're tech savvy, you can grab a copy at my repo, the [fix-vector-gfx branch](https://github.com/nayslayer/mame2003-libretro/tree/fix-vector-gfx).

The segfaults on >1 vector scaling were due to memory not being allocated properly in libretro port: there was that 2MB static memory block for video buffer that wasn't enough for anything larger than 800x600. This is now fixed.

I've also added the ability to tinker with all vector graphics options bar resolution multiplier at runtime: you don't have to restart libretro to see the results. Please note that translucency/beam width are only used with antialiased drawing.

There's a catch, though. Large resolution multipliers slow down emulation real fast. This is due to libretro needing to do pixel format conversions many times over each frame. On my 10yo PC the Tempest slows down to barely playable on glorious (but completely superfluous) 4K - a 10x higher resolution than the default. This isn't a regression, this is merely highlighted by my changes. If this is a problem, I can fuse MAME's vector renderer to libretro's video output like newer MAME versions do, at the cost of increased code complexity.

Meanwhile, a pair of screenshots:
![screenshot from 2018-10-12 18-54-15](https://user-images.githubusercontent.com/43932763/46880118-788cd080-ce50-11e8-8484-4097e7b3e6d7.png)
![screenshot from 2018-10-12 18-54-20](https://user-images.githubusercontent.com/43932763/46880119-79256700-ce50-11e8-8566-79426318300e.png)
![screenshot from 2018-10-12 18-54-38](https://user-images.githubusercontent.com/43932763/46880120-79256700-ce50-11e8-823b-d96d39219d4b.png)
![screenshot from 2018-10-12 18-54-40](https://user-images.githubusercontent.com/43932763/46880121-79256700-ce50-11e8-82c6-120098710e16.png)

**Comment by markwkidd** [comment] 2018-10-12 16:04
Wow that is looking great! Have you seen this @grant2258 @arcadez and @twinaphex? "The big one" seems at hand! :D  I won't be able to test anything personally for a bit, but I think that the results you describe will fully satisfy the bounty.

I know nothing about this more sophisticated MAME vector renderer -- and it's beyond the bounty IMO -- but are you saying that having it would be helpful for low-power systems trying to render high resolution upscaled vectors?

The mission of this core has a lot to do with supporting low power devices. If the newer vector code would do that, I think folks would be very excited. If it's worthy of a new issue and bounty I will start one, according to your preference.

**Comment by twinaphex** [comment] 2018-10-12 16:23
@markwkidd @nayslayer Sounds all great. I'm fine with any additional complexity as long as it becomes markedly faster than it is now. Also, I hope this code remains in C, it would be bad to introduce C++ code into this codebase. So that is my only precondition for this.

**Comment by Wilstorm** [comment] 2018-10-12 16:29
@nayslayer - That's looking pretty awesome, nice job! ;)

**Comment by nayslayer** [comment] 2018-10-12 16:30
As I see it, getting rid of this slowdown will help underpowered devices even if it's not noticeable, by slightly lowering their power usage. I'll look into this issue tomorrow.

It's likely I'll implement a better line drawing algorithm (capsule-based to get smoother edges) and get rid of the non-antialiased version and the resolution multiplier. Non-antialiased lines only made sense when they were rendered directly to the framebuffer (it's likely an optimization for 80386 class devices), any related speedups are dwarfed by libretro's own overhead. The resolution multiplier is merely a hack for implementing a poor's man supersampling - retroarch's current resolution should be used instead.

No new bounty is necessary, I'm doing this during procrastination anyway.

**Comment by nayslayer** [comment] 2018-10-12 16:44
Meanwhile, can anyone please find me an example of each
- a vector game that has bitmap artwork on top of it (so I can make sure I haven't messed up the resolution settings);
- a game that is noticeably slower on mame2016 than on mame2003 (so I can profile them and maybe find out a way to make the newer MAME fast enough).
Something to look into before I move on to greener grasses :)

**Comment by markwkidd** [comment] 2018-10-12 16:51
As far as superimposed bitmaps, you'll have to switch to mame2003-plus
because the artwork system is not active in standard mame2003 here. (These
parts of the codebase should be practically identical though)

The game to try is 'warrior' and there is sample artwork to use within the
I metadata folder of the mame2003-plus repository. There are known issues
with bit depth or colorspace using artwork now though. There is an issue
about that in the other repo too, with illustrations  😐

**Comment by Wilstorm** [comment] 2018-10-12 17:27
Guys, I could dig up some examples but I am not exactly sure what I am looking for. Warrior is listed as a backdrop, so is Battle Zone (bzone) where as say Armor Attack (armora) is listed as an overlay. I can get plenty of backdrop examples but there's not as many overlays.

**Comment by nayslayer** [comment] 2018-10-12 17:41
Ok, thanks. Now that I know how those look like I'll be a bit more confident that I won't break them by accident. I'll be using the [libretro's repository](https://github.com/libretro/arcade-overlays) of overlays, by the way.

**Comment by Wilstorm** [comment] 2018-10-12 18:10
Ok, great. I wasn't aware of that repository, there are some nice overlays in there, thanks! ;)

**Comment by UDb23** [comment] 2018-10-12 18:38
@nayslayer Great work !
Concerning superimposed artwork (=bezel/overlay) there are 2 options currently:
- all libretro cores (incl. lr-mame 2003) actually support overlays (thru retroarch specific .cfg file)
  Info & retropie overlay repo [here](https://github.com/udb23/rpie-ovl).

- Mame "internal" artwork support (disabled in lr-mame2003 but enabled in lr-mame2003 plus as @markwkidd said)

As test for overlay on top of vector games you can try Asteroids.
Image [here](http://thedoteaters.com/tde/wp-content/uploads/2013/03/asteroids_snap_bezel.png).

Overlay image [here](https://image.ibb.co/mObT7e/asteroid_ovl.png) by [Stuart2773](https://retropie.org.uk/forum/topic/18218/arcade-16-9-overlays-1920x1080/52)

**Comment by nayslayer** [comment] 2018-10-12 19:07
Meanwhile, I figured out that the performance only suffers when the color depth option is set to anything other than 32bpp. Kind of obvious, in retrospect. Still, I'll continue implementing a new line renderer, as the old one doesn't scale well to high resolutions. There's a callback in MAME for that so it won't be too hard.

**Comment by Wilstorm** [comment] 2018-10-12 19:31
@UDb23 - Just a quick question for clarification if possible for future reference. Looking through these older artwork files. In the artwork files ending in .art for example some files are listed as ```backdrop```, some as ```overlay``` and and some as ```bezel```, do you know the difference? I know bezel (superimposed or overlay as used here), 

Backdrop I would say behind the game sprites but overlay I'm not sure.

Battle Zone (bzone) = backdrop (inside of tank view--solid, no opacity)
Armor Attack (armora) = overlay (more like a backdrop with streets and buildings; behind game play screen)
Space Invaders (invaders) = It has all 3. Backdrop, overlay and bezel artwork. Differences?

Sorry for off topic here. If it's to much to explain I'll let it lay and thanks again @nayslayer for your amazing work!

**Comment by UDb23** [comment] 2018-10-12 21:11
@Wilstorm From Mamedevs artwork rendering system [info](https://wiki.mamedev.org/index.php/Layouts_and_Rendering_for_MAME_Artwork_System) (it's about the newer .LAY format but artwork elements definitions are valid also for older .art files).

Note: Screens means actual game graphics/sprites (see below)

**backdrops** specify the attributes of elements that are drawn first and which cover the background of the screen areas; they are rendered against each other using regular alpha blending, so they can have cut-out areas and other effects

**screens** specify the attributes of the various screens that make up a game; they are referenced by index, and are rendered on top of the backdrop layer using additive blending (alpha values applied to the source but not the destination)

**overlays** specify the attributes of elements that are drawn over top of the screens and backdrops; they are rendered on top of the screens and backdrops using RGB multiplicative blending (the RGB values of the overlays are multiplied by the RGB values of the destination)
**bezels** specify the attributes of elements that are drawn last, over all the other elements; they are rendered using regular alpha blending, like the backdrops were.
Everything in the new system is rendered back-to-front, so first all backdrop items are drawn, then all screens, then all overlays, and finally all bezels.

**Comment by UDb23** [comment] 2018-10-12 21:12
these elements basically refer to the actual (physical) artwork elements of an original arcade cabinet.

**Comment by Wilstorm** [comment] 2018-10-12 22:07
@UDb23 - Thank you so much for the information and explanation. I've been confused on the differences for a while and the breakdown makes it much more understandable. 

I find the whole thing pretty exciting as AdvMAME is miles ahead of any Libretro core in relation to vector games so this could be a major turning point. Really it's good news all around.

**Comment by nayslayer** [comment] 2018-10-18 22:06
Psst, missed me? Sorry for the delay - had RL issues to attend to. I'm done with the issue for now - it's done as per the original specification and a PR is made. The settings should now work without problems.

I've failed to do the extras, though.

The performance issue, for one, stems not from the core, but from Retroarch being slow at stretching images from internal resolution. This actually affects all cores and all drivers I've tested yet (even the half-dead gdi one). This is evidenced by high (70% total) amounts of time spent in either the graphics drivers or the gdi image stretching functions.

This can probably be fixed in a number of ways, none of them easy or without further problems: making Retroarch use hardware for image stretching (GPU has texture samplers for that) - this is speculative; making the mame2003 core use hardware opengl context to do the same - this will merely push the problem into obscurity;  using the display's native resolution to bypass stretching - this would've been an ideal solution if libretro's API exposed display resolutions list =(

The non-antialiased lines remain as I missed the point of mame2003 originally. It's just not the default anymore. Still, rendering lines takes up to 15% of the total CPU time so the setting will stay for anyone needing to squeeze some extra performance.

I also wanted to make a new line renderer to fix the disjoint edges but failed to do so =/ The idea was to use bresenham's algo to plot a line and tesselate around it horizontally (to minimize cache thrashing), checking for when a pixel is inside the radius. This worked great for me when it was backed by a GPU but it's 5x or so slower than the current implementation. And I'm wary of messing with the existing algo =/

Well, if there's anything more I can help with, please @ me.

**Comment by markwkidd** [comment] 2018-10-19 13:54
@nayslayer now that your patch is merged into the core, I would suggest that you begin the BountySource claim procedure. That process involves contacting the donors and either getting their thumbs up on awarding the bounty, or after a certain amount of time it happens automatically if someone doesn't reply.

Now that the patch is merged, donors (and others) can try out your improvements easily from the buildbot starting in a few hours.

**Comment by markwkidd** [comment] 2018-10-19 15:15
The BountySource API requires this issue to be closed in order for @nayslayer to advance to the next phase, but that does not mean folks shouldn't continue commenting here. I guess can always reopen the issue later once BountySource is happy.

**Comment by nayslayer** [comment] 2018-10-19 15:46
@markwkidd @dankcushions Wow, you guys sure work fast. Thanks for your support :) I recognize that the solution isn't exactly ideal yet - there are a few extra tough nuts to crack in Retroarch and libretro itself as I mentioned before, but I'll keep those in mind for now if I can think of a solution. I'll file those as separate issues once I get the hang of these codebases.

Especially I haven't expected it to work in full hd on an RPi - much obliged, @dankcushions! You're right that this is a sort of a bandwidth issue - the core's output needs to be stretched before it's output to the screen and this is done on CPU for now. You're also right that libretro reporting the current resolution to the core is a possible solution. It's also a sort of a low-hanging fruit - all the data needed is there already. I'll make sure to try and push the necessary changes to libretro once I get my current work sorted.

Do not hesitate to @ me if there's a problem! For now I'll return to working on my recompiler work as I've been neglecting that, but now that I'm acquainted with mame code I'll probably fix a few issues more this year!

**Comment by markwkidd** [comment] 2018-10-19 15:48
@nayslayer if I was going to ask you one more thing while you're still "fresh" on this issue: would be can you help write up an issue for the RetroArch repo about the video scaling?

You have a clear writing style and I think it would be very useful to have a place where RetroArch devs could comment specifically on that. I am willing to do it if you aren't, but firsthand experience is usually always better!

**Comment by nayslayer** [comment] 2018-10-19 16:00
@markwkidd Sure! I'll investigate those some more, then file the issues. I could've done that myself by now but there's literally a thousand issues open in Retroarch alone so I'm not sure this wasn't suggested already or if the devs have other plans. I'll have skim over the issues list first, then make a prototype for the needed APIs... This'll take some time, though. I'll be sure to contact you once I'm ready - your work was invaluable so far.

**Comment by markwkidd** [comment] 2018-10-19 21:43
BountySource is acting silly and I think it may be because I reopened this issue. Closed again now, but open for discussion regardless.

**Closed** 2018-10-19 21:42 UTC

**Comment by ewancube** [comment] 2018-10-19 22:18
Yeah thanks - I wasn’t able to vote on the bounty with it open. Done now. ✅

**Comment by markwkidd** [comment] 2018-10-20 02:28
As another possible RetroArch issue report, I find that the XMB "Quick Menu" is unusable when the vector resolution multiplier is in use. On the other hand, RGUI is stretched but totally usable.

![screenshot 2018-10-19 22 22 12](https://user-images.githubusercontent.com/19554678/47250389-156de180-d3ee-11e8-931f-8fa6b799ca45.png)
![screenshot 2018-10-19 22 23 46](https://user-images.githubusercontent.com/19554678/47250391-1868d200-d3ee-11e8-84ef-a89dded7a72d.png)

**Comment by markwkidd** [comment] 2018-10-28 16:07
I was chatting with @barbudreadmon who is working on the Kronos core about how that core handles changing its resolution multiplier core option. barbudreadmon suggested that it should be possible to use SET_AV_INFO to change the resolution without having to restart mame2003

I've used this exact same text to start a new issue to explore this possibility once there is time, and I'm merely posting here in order to create a link between the two issues: https://github.com/libretro/mame2003-plus-libretro/issues/435

**Comment by grant2258** [comment] 2018-10-28 16:34
yea had to do this with setting the sample rate on the fly as well for mame 2003

**Comment by grant2258** [comment] 2018-10-28 17:53
if ( (  Machine->drv->frames_per_second < 47 ) && (Machine->sample_rate >= 30000) )
	{ 
		struct retro_system_av_info info;
		retro_get_system_av_info(&info);
		info.timing.sample_rate= 22050;
		Machine->sample_rate=22050;
		samples_per_frame = Machine->sample_rate / Machine->drv->frames_per_second;
		environ_cb(RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO, &info);
	}

**Comment by grant2258** [comment] 2018-10-28 17:55
that the way dan wanted it left on mame2003 we done it a little differently saves a restart
