### ISSUE TITLE
mame2003 "will have errors" on 64-bit platforms

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#83] opened 2017-02-25 03:59 UTC
This issue is sourced from the original MAME 2003 readme which said that the core  "Will have errors on 64-bit platforms." As it is, the statement is not especially helpful, and leads to more questions:

* What kind of errors? How serious -- do some games only work on 32 bit platforms?
* Should users seek out 32 bit compiles of the core and avoid 64-bit compiles? Or does it mean that running any version of the core on a 64 operating system will lead to these errors?

**Comment by markwkidd** [comment] 2017-03-06 07:23
The first version of the README has a bit more detail -- the concern is pointers being cast to 32 bits: https://github.com/libretro/mame2003-libretro/blob/86c79bc4af85310cbba270db83316e1669b0b059/README#L7

I'll look through a few more old README commits to see if there are any other notes to explain this warning.

**Comment by markwkidd** [comment] 2017-03-06 07:45
I believe I have found the source of this concern amongst the reference links to anthrofox.org at the bottom of the README: **[Debugging xmame Segfaults on X86-64](http://www.anthrofox.org/code/mame/64bitclean/index.html)**

**Comment by markwkidd** [comment] 2017-06-23 06:10
@r-type you might be the best qualified person to answer this question -- should there ever be x64 compiles of this core if it has inherent issues with that architecture?

**Comment by barbudreadmon** [comment] 2017-10-05 07:06
On my x86_64, Street fighter 2 crashes on the select champ screen on the following code : 

> 0x00007fffdd93f7aa in advance () at src/sound/ym2151.c:2179
2179					(op+0)->phase += ( (PSG->freq[ kc_channel + (op+0)->dt2 ] + (op+0)->dt1) * (op+0)->mul ) >> 1;

**Comment by rb6502** [comment] 2017-12-28 01:23
64-bit compatibility in MAME wasn't seriously worked on until around 2006/2007, so if this version runs on 64-bit at all it's kind of a miracle.

**Comment by twinaphex** [comment] 2017-12-28 01:35
It does yeah, I think some 64-bit patches have been submitted as well over the years (as well as some big endian fixes).

**Comment by grant2258** [comment] 2018-03-18 20:03
well if its going to cause issues surely we can just compile with -m32

**Comment by vaguerant** [comment] 2018-03-22 10:03
I was about to file an issue about the fact that Elevator Action Returns doesn't work as a "regression", as it fails on my 64-bit Android tablet, but seeing this issue, it looks like this may be what I'm encountering.

On my Raspberry Pi, I'm running cb4826a, while my Android tablet runs df8e01f. Elevator Action Returns plays "fine" (slow) on the Pi, but fails to launch with an in-game `SERVICE SW ERROR` on Android.

**Comment by mahoneyt944** [comment] 2021-01-03 01:13
I'm not sure this is an issue anymore, as it wasn't clearly documented in the first place. I tried elevator action on my 64 bit android phone and it played fine. I'm going to close this but if anything more is found out we can open it back up.

**Closed by mahoneyt944** 2021-01-03 01:13 UTC

**Comment by Wilstorm** [comment] 2021-01-03 02:34
@mahoneyt944 - Did you try Elevator Action or Elevator Action Returns, two different games. Returns is much more demanding. It’s a good game, I think Grant was looking at getting it running quicker potentially.

**Comment by mahoneyt944** [comment] 2021-01-03 02:40
I tried both. Both ran fine on my Android.
![elevator-210102-213909](https://user-images.githubusercontent.com/49591133/103470678-1bd4a380-4d43-11eb-823e-c279575a9b9c.png)
![elvactr-210102-213834](https://user-images.githubusercontent.com/49591133/103470679-1c6d3a00-4d43-11eb-9b3e-780dc7b77eed.png)

**Comment by Wilstorm** [comment] 2021-01-03 10:29
Ah ok, nice I wasn’t sure when you didn’t add ‘Returns’. Both great games but entirely different besides the name.
