### ISSUE TITLE
Cannot input coins via gamepad in some games if hotkey is select button

### ISSUE THREAD

**Issue by kalehrl** [libretro/mame2003-libretro#8] opened 2015-02-24 10:10 UTC
I'm unable to input credits by using gamepad select button in some games like galaxian, gnga, circusc, puckmana if hotkey is select button.
In some others like bombjack, arkangc, 1942a and timeplt it works fine.
If I disable hotkey button, everything works fine.
Do you have any ideas what may be causing this?

**Comment by joolswills** [comment] 2015-09-19 04:35
I can confirm this.

**Comment by kalehrl** [comment] 2015-11-15 14:56
Seriously guys, please fix this!

**Comment by joolswills** [comment] 2015-11-15 15:35
See https://github.com/libretro/RetroArch/issues/2230 - the fix is to use a hotkey enable button that is not assigned to anything.

**Comment by kalehrl** [comment] 2015-11-15 18:21
Why the need for the workaround instead of a proper fix?
I don't use hotkey button at all.
I just set up my controller manually and use the predefined hotkeys like start+select for quitting RA, select+x for popup menu etc.

**Comment by AtomizerZero** [comment] 2015-12-24 23:14
kalehrl, you say you dont use a hotkey... so how do you use Select+other button to use hotkeys?

**Comment by kalehrl** [comment] 2015-12-25 14:10
I meant I use the default setup whatever it is.
I haven't made any changes to the hotkeys.

**Comment by objectchris** [comment] 2015-12-25 21:45
The default is for select to be the hotkey, which is what you've got. You're problem is caused by the issue joolswills linked to. Libretro/retroarch won't fix that one but retropie have an open issue to handle it in their fork, hopefully in the near future :) https://github.com/RetroPie/RetroPie-Setup/issues/1072

**Comment by objectchris** [comment] 2016-02-21 16:04
This is resolved for Retropie users in patch https://github.com/RetroPie/RetroPie-Setup/pull/1278

**Comment by hizzlekizzle** [comment] 2016-02-21 16:11
@joolswills 
Would you mind throwing that patch into a PR for RetroArch? I suspect @twinaphex would be interested in adding it upstream.

**Comment by joolswills** [comment] 2016-02-22 10:27
it is mentioned in an issue on retroarch - I don't believe they want the change currently.

**Closed** 2018-03-25 00:47 UTC
Labels: wontfix
