### ISSUE TITLE
[Enhancement] Vector resolution settings

### ISSUE THREAD

**Issue by dankcushions** [libretro/mame2003-libretro#30] opened 2016-05-20 13:38 UTC
It would be good to be able to change the mame vector resolution options from the default 640x480, which is jaggy on larger screens. I thought the best approach would just be to use the current resolution (it programmatically corrects the ratio), but ran into problems at a very early stage:

https://github.com/dankcushions/mame2003-libretro/commit/31da6de6ef60c1236b36eeb3ed6dccebea9860e5

```
        // Set all options before starting the game
        options.samplerate = sample_rate;
        options.ui_orientation = uiModes[rotateMode];
        options.vector_intensity = 1.5f;
        options.skip_disclaimer = skip_disclaimer;
        options.use_samples = samples;
        options.cheat = cheats;
        // Testing vector stuff
        options.vector_width = 1920;
        options.vector_height = 1080;
```

Any test resolutions I put in above around 800x600 cause a segfault in the memory handlers. I'm not very familiar with debugging this sort of issue in C so I've given up, but if anyone else wants to have a go - please!

**Comment by Redemp** [comment] 2016-11-06 22:15
Second this. Would love to be able to change the Vector resolution

**Comment by markwkidd** [comment] 2018-03-03 01:33
@arcadez do you know how to increase the resolution in a situation like this?

**Comment by UDb23** [comment] 2018-03-03 05:55
In another request it is mentioned that the [alt renderer](https://forums.libretro.com/t/forcing-internal-resolution-in-mame-core/11236/8) can handle higher res. No clue if this is implemented/can help w mame 2003 on a Pi.

**Comment by dankcushions** [comment] 2018-03-03 08:56
i’m curious if this works in standalone mame 0.78 windows binary.

**Comment by markwkidd** [comment] 2018-03-03 09:53
@dankcushions I've been able to have an interesting result by making your modification to `libretro.c`:

        // Testing vector stuff
        options.vector_width = 1920;
        options.vector_height = 1080;

And then making one change to `mame.c`:

At line 694:
	/* if we're a vector game, override the screen width and height */
	if (Machine->drv->video_attributes & VIDEO_TYPE_VECTOR)
		scale_vectorgames(640, 480, &bmwidth, &bmheight);

It seems that any target horizontal value greater than 643 in the first `scale_vectorgames` call (which gets rounded down to 640) will cause a segfault. But once `artwork_create_display` has been called it is safe to call the second `scale_vectorgames` with a horizontal target resolution that higher.

The result isn't exactly what we're looking for but maybe this is a clue.

**Comment by dankcushions** [comment] 2018-03-03 13:07
@markwkidd oh, so it works if you only pass the higher resolution only in the second call?

i wonder what the point is in the first call if it gets duplicated later on? perhaps the screen height/width is referred to in some of the interim calls?

**Comment by markwkidd** [comment] 2018-03-03 16:26
Yes, well it does get bigger but the display isn't right if you wait to add the higher resolution later. 

@dankcushions The default windows settings look much better for vector games.

One apparent difference between mame0.78 and mame2003 is that the vector antialias setting is turned on for mame 0.78.

I tried setting antialias=1 for mame2003 and it freezes while setting up the screen here with the retroarch d3d9 video driver.

In addition to `mame.c`, `libretro/video.c` and `vector.c` may be involved in all this

**Comment by markwkidd** [comment] 2018-03-06 23:32
@dankcushions would you be OK with making this issue into a bounty? I have $10 I can allocate to it, but I think this is a good candidate for a bounty and who knows -- maybe others would pitch in.

As the OP you would need to give your blessing on the terms. My thought would be just that mame2003 vector games would need to look as good as mame 0.78. `tempest.zip` could be a reference point.

What do you think?

**Comment by markwkidd** [comment] 2018-03-07 01:40
I decided to prepare a visual comparison of default mame 0.78 versus mame2003 with Tempest. I noticed that mame2003 is rendering at a higher, but un-anti-aliased resolution. Maybe the higher resolution is a clue -- rendering at an unoptimal resolution, etc?

![tempest-comparison](https://user-images.githubusercontent.com/19554678/37068813-953bc3f0-217e-11e8-8a0e-af6f31239e75.png)
I hope this visual will help, at least.

**Comment by caver01** [comment] 2018-03-07 08:18
I would contribute to that bounty if it resulted in the ability to set resolution to match my display. Better yet, if it also included the other typical vector adjustments: antialiasing, beam_width, intensity, transparency, flicker.

**Comment by dankcushions** [comment] 2018-03-07 09:40
I guess my issue is that advmame exists and does these games correctly already. mame 0.78’s emulation of vector games is somewhat preliminary so I wonder how worthwhile improvements are. how does mame2010 fare, here?

it’s also tricky because even if the issue is fixed, it’s still up to the user to manually set the desired resolution via core options. as far as i know a core doesn’t know retroarch’s current video resolution, so it’s a bit inelegant.

that said, i am still curious what the problem is. if a bounty is still wanted I don’t mind opening it :)

**Comment by markwkidd** [comment] 2018-03-07 18:40
Adding the remaining vector options is not such a problem, so I went ahead and did so with this PR: https://github.com/libretro/mame2003-libretro/pull/331

I noticed that beam_width isn't affecting `tempest.zip` but the other settings seem to be working ok.

**Comment by markwkidd** [comment] 2018-03-07 18:48
Here's how I think the bounty requirement could be defined:

1. Vector games should appear as sharp and antialiased with mame2003's default settings as the same games do with mame 0.78's default settings.
2. The MAME antialias option itself should be fixed, and made toggle-able
3. (Optional - not sure this is as important?) The MAME vector resolution option should be fixed to allow users to manually set vector games to render at higher resolutions

**Comment by markwkidd** [comment] 2018-03-07 19:24
(libretro devs are watching over us today -- the new vector settings have been merged)

**Comment by markwkidd** [comment] 2018-03-10 08:45
I am realizing two things 1) I've kind of monopolized this issue with my bounty chat and 2) I'm still pretty jazzed about trying to raise a bounty.

Therefore I have decided to start an issue framed narrowly on what could be accomplished through a bounty. Maybe something will happen!

**Comment by UDb23** [comment] 2018-03-10 10:40
As AdvanceMame already supports high res vector rendering (work nicely at 1080p) I would suggest the bounty should provide a solution for higher resolutions than just 470x642 in Mame2003.

**Comment by markwkidd** [comment] 2018-03-10 15:00
Agreed @UDb23 . I have updated the text of the bounty to reflect that the resolution scaling option should work as part of the requirement. Thanks!

**Comment by markwkidd** [comment] 2018-03-25 01:09
One thing I can add is that the antialiasing code in mame2003 is essentially identical to the current AdvanceMAME antialias code.

To me that implies too things: mame2003 vectors should be able to look just as good as AdvanceMAME and that the issue may lie in either the libretro port or something like compiler tags.

**Comment by grant2258** [comment] 2018-04-13 17:08
the problem is mame.c is set before  we start if you want to change flags this way mark see how I done it in fix for the sound in mame2003+  

https://github.com/libretro/mame2003-plus-libretro/commit/f2b44c8f4cff47be923a85c1ed8fbe2d77981220


I have since refined it to https://github.com/libretro/mame2003-libretro/commit/c9865f3075be5dc3bc4a0063a2e7894c26bc6d4e

**Comment by markwkidd** [comment] 2019-01-18 14:34
This issue be resolved in the latest build. :)

**Closed** 2021-01-03 01:45 UTC
